import { ServicePackage } from './types';

export const SERVICE_PACKAGES: ServicePackage[] = [
  {
    id: 'starter-launchpad',
    name: 'Starter Launchpad',
    tagline: 'Modern Web Presence for Local UAE Businesses',
    priceAed: '4,500',
    priceNote: 'One-time investment · 0% commission',
    turnaround: '10–14 Business Days',
    badge: 'Fast Launch',
    popular: false,
    description:
      'Ideal for new or established local clinics, salons, cafes, and service firms needing a fast, high-converting modern website to replace an outdated page.',
    features: [
      'Bespoke, Mobile-First Website (Up to 5 Pages)',
      'Custom Brand Design (No generic templates)',
      'Local Google Maps & Business Profile Setup',
      'Direct WhatsApp 1-Tap Chat Integration',
      'Contact & Lead Capture Forms with Email Alerts',
      'Fast Cloudflare CDN Hosting & SSL Setup',
      'Basic On-Page SEO for Dubai Search Terms',
      '15-Minute Admin Handover Video & 30-Day Support',
    ],
    bestFor: 'Local businesses looking for a credible digital storefront to capture Google search visitors.',
  },
  {
    id: 'growth-commerce',
    name: 'Growth & Direct Commerce',
    tagline: 'Zero-Commission Ordering, Booking & Sales',
    priceAed: '8,900',
    priceNote: 'One-time investment · Keep 100% of sales',
    turnaround: '2–3 Weeks',
    badge: 'Most Popular',
    popular: true,
    description:
      'Tailored for restaurants, cafes, e-commerce shops, and clinics ready to stop paying 25–35% commissions to third-party delivery and booking aggregators.',
    features: [
      'Complete Online Ordering, Store or Booking System',
      'Zero Monthly Commissions — You keep 100% of sales',
      'Apple Pay, Google Pay & Local UAE Payment Gateways',
      'Menu & Product Catalog Manager (Edit prices instantly)',
      'Direct WhatsApp Order & Appointment Dispatch',
      'Google Ads & Meta Pixel Conversion Tracking Setup',
      'Advanced Local Dubai SEO (Neighborhood 3-Pack)',
      'Lead Generation & Automated Email Capture Sequences',
      '60-Day Priority Maintenance & UAE WhatsApp Support',
    ],
    bestFor: 'Cafes, restaurants, retail shops, and aesthetic clinics ready to turn visitors into repeat buyers.',
  },
  {
    id: 'enterprise-custom',
    name: 'Enterprise Scale & Custom Apps',
    tagline: 'Custom Web Applications & Full Digital Growth',
    priceAed: '16,500',
    priceNote: 'Starting from · Bespoke scope',
    turnaround: '3–5 Weeks',
    badge: 'Full Scale',
    popular: false,
    description:
      'Engineered for corporate firms, franchise groups, and high-volume brands requiring bespoke workflows, portals, or full-funnel Google Ads campaign management.',
    features: [
      'Custom Full-Stack Web Application (Next.js / Node.js)',
      'Multi-Location or Franchise Management System',
      'Customer Portal, Client Dashboard or Gated VIP Area',
      'Full Multilingual Arabic & English Localization',
      'Custom API & ERP Integrations (POS, CRM, Couriers)',
      'Google Ads & Performance Marketing Strategy Setup',
      'DFSA / High-Level Security & Regulatory Hardening',
      'Dedicated Dubai Account Manager (In-Person or Zoom)',
      'Quarterly Performance Audits & Ongoing SLA Support',
    ],
    bestFor: 'High-growth brands, multi-branch groups, and firms running large paid Google Ads ad spend.',
  },
];
